In [89]:
import numpy as np

a = np.matrix([[1, 2, 3], [2, 2, 2], [0, 0, 0], [5, 4, 3]])
m = a.shape[0]
a = np.c_[a, np.ones(m)]
print(a)
w = np.matrix([[1, 2, 3, 0], [1,3,5,0]])

def mul1(x):
    return x

w = mul1(w)
print(w)

m = a.shape[0]
w.shape[0]


[[1. 2. 3. 1.]
 [2. 2. 2. 1.]
 [0. 0. 0. 1.]
 [5. 4. 3. 1.]]
[[1 2 3 0]
 [1 3 5 0]]


2

In [78]:
z = a*w.transpose()

z

matrix([[14, 22],
        [12, 18],
        [ 0,  0],
        [22, 32]])

In [ ]:
m*in  and out * in want m*out

In [54]:
print(w*(np.asmatrix(a[0]).transpose())

SyntaxError: unexpected EOF while parsing (<ipython-input-54-13e1217b9c6b>, line 1)

In [1]:
print(w*(np.asmatrix(a[0]).transpose())

SyntaxError: unexpected EOF while parsing (<ipython-input-1-13e1217b9c6b>, line 1)

In [3]:
def autoencoder_cost_and_grad(theta, visible_size, hidden_size, lambda_, data):
"""
The input theta is a 1-dimensional array because scipy.optimize.minimize expects
the parameters being optimized to be a 1d array.
First convert theta from a 1d array to the (W1, W2, b1, b2)
matrix/vector format, so that this follows the notation convention of the
lecture notes and tutorial.
You must compute the:
    cost : scalar representing the overall cost J(theta)
    grad : array representing the corresponding gradient of each element of theta
"""
  training_size = data.shape[1]
  # unroll theta to get (W1,W2,b1,b2) #
  W1 = theta[0:hidden_size*visible_size]
  W1 = W1.reshape(hidden_size,visible_size)

  W2 = theta[hidden_size*visible_size:2*hidden_size*visible_size]
  W2 = W2.reshape(visible_size,hidden_size)

  b1 = theta[2*hidden_size*visible_size:2*hidden_size*visible_size + hidden_size]
  b2 = theta[2*hidden_size*visible_size + hidden_size: 2*hidden_size*visible_size + hidden_size + visible_size]

  #feedforward pass
  a_l1 = data

  z_l2 = W1.dot(a_l1) + numpy.tile(b1,(training_size,1)).T
  a_l2 = sigmoid(z_l2)

  z_l3 = W2.dot(a_l2) + numpy.tile(b2,(training_size,1)).T
  a_l3 = sigmoid(z_l3)

  #backprop
  delta_l3 = numpy.multiply(-(data-a_l3),numpy.multiply(a_l3,1-a_l3))
  delta_l2 = numpy.multiply(W2.T.dot(delta_l3),
                             numpy.multiply(a_l2, 1 - a_l2))

  b2_derivative = numpy.sum(delta_l3,axis=1)/training_size
  b1_derivative = numpy.sum(delta_l2,axis=1)/training_size

  W2_derivative = numpy.dot(delta_l3,a_l2.T)/training_size + lambda_*W2
  #print(W2_derivative.shape)
  W1_derivative = numpy.dot(delta_l2,a_l1.T)/training_size + lambda_*W1

  W1_derivative = W1_derivative.reshape(hidden_size*visible_size)
  W2_derivative = W2_derivative.reshape(visible_size*hidden_size)
  b1_derivative = b1_derivative.reshape(hidden_size)
  b2_derivative = b2_derivative.reshape(visible_size)


  grad = numpy.concatenate((W1_derivative,W2_derivative,b1_derivative,b2_derivative))
  cost = 0.5*numpy.sum((data-a_l3)**2)/training_size + 0.5*lambda_*(numpy.sum(W1**2) + numpy.sum(W2**2))
  return cost,grad

IndentationError: expected an indented block (<ipython-input-3-a5b709bbfd63>, line 11)